---
title: Eric Stern
timezone: UTC
collections:
  posts:
    title: Journal
    output: true
  work:
    title: Projects
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/journal/:title/"
    layout: entries
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    layout: projects
    general:
      project_color: "#222"
      project_text_color: "#fff"
      project_details: Role & year
    is_columns: false
    sections:
    - type: text
      body: Text field. Body copy goes here.
    - type: center-image
      image: 
      press_url: http://google.com
    - type: color-pallete
      image: 
    - type: image-grid
      left_image: 
      right_image: 
    - type: divider
    - type: vimeo, youtube
      id: 123456789
      ratio: wide, square, or standard
    - type: media-grid
      press_items:
        - logo:
          press_url: http://google.com   
    - type: media-plan
      plan_file: 
      button_text: View Media Plan
- scope:
    path: index.markdown
    type: pages
  values:
    navigation:
      item:
      - projects: Apparel Art Designs
        cover_image: "/uploads/interns-1.jpg"
- scope:
    path: about.markdown
    type: pages
  values:
    permalink: "/about"
    layout: about
    page_heading: ''
    bio_image: ''
- scope:
    path: work.markdown
    type: pages
  values:
    permalink: "/work"
    layout: work
- scope:
    path: contact.markdown
    type: pages
  values:
    permalink: "/contact"
    layout: contact
    page_heading: ''
email: es@ericstern.works
description: 
keywords: 
baseurl: 
url: 
twitter_username: ericstern
tagline: Creator. Storyteller. Achiever.
google_analytics:
  tracking_id: UA-113777497-1
markdown: kramdown
plugins:
- jekyll-redirect-from
sass:
  style: compressed
permalinks: pretty
profile_image: 
