---
title: Eric Stern
timezone: UTC
collections:
  posts:
    title: Journal
    output: true
  work:
    title: Projects
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_dark: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/journal/:title/"
    layout: entries
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    layout: projects
    general:
      project_color: "#222"
      project_text_color: "#fff"
      project_details: Role & year
      color_pallete_image: 
      pallete_is_first: 
    sections:
    - type: text
      body: Project copy goes here.
    - type: image-grid
      left_image: 
      right_image: 
    - type: center-image
      image: 
- scope:
    path: index.markdown
    type: pages
- scope:
    path: about.markdown
    type: pages
  values:
    permalink: "/about"
    layout: about
    page_heading: ''
    bio_image: ''
- scope:
    path: work.markdown
    type: pages
  values:
    permalink: "/work"
    layout: work
- scope:
    path: contact.markdown
    type: pages
  values:
    permalink: "/contact"
    layout: contact
    page_heading: ''
email: hi@ericstern.works
description: I'm Eric Stern
baseurl: 
url: 
twitter_username: ericstern
tagline: Creator. Storyteller. Achiever.
google_analytics:
  tracking_id: UA-123456789-1
markdown: kramdown
plugins: 
sass:
  style: compressed
permalinks: pretty
profile_image: 
