---
title: Eric Stern
timezone: UTC
collections:
  posts:
    title: Journal
    output: true
  work:
    title: Projects
    output: true
    permalink: "/:collection/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_dark: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/journal/:title/"
    layout: entries
- scope:
    path: ''
    type: work
  values:
    permalink: "/work/:title/"
    layout: projects
    general:
      client: 
      project_year: 
      project_url: 
      cover_image: 
    services:
    - type: 
    sections:
    - type: text
      body: 
- scope:
    path: index.markdown
    type: pages
  values:
    projects:
    - First Featured Project
    - Second Featured Project
    navigation:
    - Page Slug
    - Contact Email
- scope:
    path: about.markdown
    type: pages
  values:
    permalink: "/about"
    layout: about
    page_heading: ''
    bio_image: ''
- scope:
    path: work.markdown
    type: pages
  values:
    permalink: "/work"
    layout: work
- scope:
    path: contact.markdown
    type: pages
  values:
    permalink: "/contact"
    layout: contact
    page_heading: ''
email: hi@ericstern.works
description: I'm Eric Stern
baseurl: 
url: 
twitter_username: ericstern
tagline: Creator. Storyteller. Acheiver.
google_analytics:
  tracking_id: UA-123456789-1
markdown: kramdown
plugins: 
sass:
  style: compressed
permalinks: pretty
profile_image: 
